AWSTemplateFormatVersion: '2010-09-09'
Description: 'Flight Schedule Pro - CloudFront Distribution for Frontend CDN'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - production
    Description: Environment name
  
  ProjectName:
    Type: String
    Default: flight-schedule-pro
    Description: Project name for resource naming

Resources:
  # Cache Policy for optimized caching
  CachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Name: !Sub '${ProjectName}-${Environment}-cache-policy'
        Comment: Optimized cache policy for static assets
        DefaultTTL: 31536000  # 1 year
        MaxTTL: 31536000
        MinTTL: 0
        ParametersInCacheKeyAndForwardedToOrigin:
          EnableAcceptEncodingGzip: true
          EnableAcceptEncodingBrotli: true
          CookiesConfig:
            CookieBehavior: none
          HeadersConfig:
            HeaderBehavior: none
          QueryStringsConfig:
            QueryStringBehavior: none

  # CloudFront Origin Access Control
  CloudFrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub '${ProjectName}-${Environment}-oac'
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  # CloudFront Distribution
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Sub 'CloudFront distribution for ${ProjectName} ${Environment}'
        DefaultRootObject: index.html
        HttpVersion: http2and3
        PriceClass: PriceClass_100
        Origins:
          - Id: S3Origin
            DomainName:
              Fn::ImportValue: !Sub '${ProjectName}-${Environment}-FrontendBucketDomainName'
            S3OriginConfig:
              OriginAccessIdentity: ''
            OriginAccessControlId: !Ref CloudFrontOriginAccessControl
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          # Cache policy for better performance (replaces ForwardedValues)
          CachePolicyId: !Ref CachePolicy
          # Optimized caching: 1 year for static assets, 0 for HTML
          MinTTL: 0
          DefaultTTL: 31536000  # 1 year for static assets
          MaxTTL: 31536000
        # Cache behaviors for different file types
        CacheBehaviors:
          - PathPattern: '*.js'
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
            CachedMethods:
              - GET
              - HEAD
            Compress: true
            CachePolicyId: !Ref CachePolicy
            MinTTL: 31536000  # 1 year for JS files
            DefaultTTL: 31536000
            MaxTTL: 31536000
          - PathPattern: '*.css'
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
            CachedMethods:
              - GET
              - HEAD
            Compress: true
            CachePolicyId: !Ref CachePolicy
            MinTTL: 31536000  # 1 year for CSS files
            DefaultTTL: 31536000
            MaxTTL: 31536000
          - PathPattern: '*.png'
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
            CachedMethods:
              - GET
              - HEAD
            Compress: false
            CachePolicyId: !Ref CachePolicy
            MinTTL: 31536000  # 1 year for images
            DefaultTTL: 31536000
            MaxTTL: 31536000
          - PathPattern: '*.jpg'
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
            CachedMethods:
              - GET
              - HEAD
            Compress: false
            CachePolicyId: !Ref CachePolicy
            MinTTL: 31536000  # 1 year for images
            DefaultTTL: 31536000
            MaxTTL: 31536000
          - PathPattern: '*.svg'
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
            CachedMethods:
              - GET
              - HEAD
            Compress: true
            CachePolicyId: !Ref CachePolicy
            MinTTL: 31536000  # 1 year for SVG
            DefaultTTL: 31536000
            MaxTTL: 31536000
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 300
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 300
        Logging:
          Bucket:
            Fn::Sub:
              - '${LogsBucket}.s3.amazonaws.com'
              - LogsBucket:
                  Fn::ImportValue: !Sub '${ProjectName}-${Environment}-LogsBucketName'
          Prefix: cloudfront-logs/
          IncludeCookies: false
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

Outputs:
  CloudFrontDistributionId:
    Description: CloudFront Distribution ID
    Value: !Ref CloudFrontDistribution
    Export:
      Name: !Sub '${ProjectName}-${Environment}-CloudFrontDistributionId'

  CloudFrontDomainName:
    Description: CloudFront Domain Name
    Value: !GetAtt CloudFrontDistribution.DomainName
    Export:
      Name: !Sub '${ProjectName}-${Environment}-CloudFrontDomainName'

  CloudFrontUrl:
    Description: CloudFront URL
    Value: !Sub 'https://${CloudFrontDistribution.DomainName}'
    Export:
      Name: !Sub '${ProjectName}-${Environment}-CloudFrontUrl'


