AWSTemplateFormatVersion: '2010-09-09'
Description: 'Flight Schedule Pro - RDS PostgreSQL Database'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - production
    Description: Environment name
  
  ProjectName:
    Type: String
    Default: flight-schedule-pro
    Description: Project name for resource naming

  DBInstanceClass:
    Type: String
    Default: db.t3.micro
    Description: Database instance type
    AllowedValues:
      - db.t3.micro
      - db.t3.small
      - db.t3.medium

  DBAllocatedStorage:
    Type: Number
    Default: 20
    MinValue: 20
    MaxValue: 100
    Description: Allocated storage size in GB

  DBName:
    Type: String
    Default: flight_schedule_pro
    Description: Database name

  DBMasterUsername:
    Type: String
    Default: postgres
    Description: Database master username
    NoEcho: true

  DBMasterPassword:
    Type: String
    NoEcho: true
    Description: Database master password (min 8 chars)
    MinLength: 8

  # VPC Configuration (using default VPC for demo)
  VpcId:
    Type: AWS::EC2::VPC::Id
    Default: vpc-03cd6462b46350c8e
    Description: VPC ID (using default VPC for demo)

  Subnet1Id:
    Type: AWS::EC2::Subnet::Id
    Default: subnet-0dcbb744fa27d655a
    Description: Subnet 1 ID (default subnet in us-east-1a)

  Subnet2Id:
    Type: AWS::EC2::Subnet::Id
    Default: subnet-0ec51c4b01051563c
    Description: Subnet 2 ID (default subnet in us-east-1b)

Resources:
  # DB Subnet Group (using default subnets)
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: !Sub '${ProjectName}-${Environment}-db-subnet-group'
      DBSubnetGroupDescription: Subnet group for RDS PostgreSQL (demo - using default VPC)
      SubnetIds:
        - !Ref Subnet1Id
        - !Ref Subnet2Id
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-db-subnet-group'

  # Security Group for RDS (simplified for demo - allows access from anywhere)
  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${ProjectName}-${Environment}-db-sg'
      GroupDescription: Security group for RDS PostgreSQL (demo - public access)
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 0.0.0.0/0
          Description: Allow PostgreSQL access from anywhere (DEMO ONLY)
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-db-sg'

  # DB Parameter Group removed for demo - using RDS default parameter group

  # RDS PostgreSQL Instance
  DBInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot
    UpdateReplacePolicy: Snapshot
    Properties:
      DBInstanceIdentifier: !Sub '${ProjectName}-${Environment}-db'
      DBName: !Ref DBName
      Engine: postgres
      EngineVersion: '14.19'
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: !Ref DBAllocatedStorage
      StorageType: gp3
      StorageEncrypted: true
      MasterUsername: !Ref DBMasterUsername
      MasterUserPassword: !Ref DBMasterPassword
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups:
        - !Ref DBSecurityGroup
      # Using default parameter group for demo
      BackupRetentionPeriod: 7
      PreferredBackupWindow: '03:00-04:00'
      PreferredMaintenanceWindow: 'sun:04:00-sun:05:00'
      EnableCloudwatchLogsExports:
        - postgresql
        - upgrade
      DeletionProtection: !If [IsProduction, true, false]
      MultiAZ: !If [IsProduction, true, false]
      PubliclyAccessible: true
      AutoMinorVersionUpgrade: true
      CopyTagsToSnapshot: true
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-db'
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # Read Replica for Dashboard Queries (Production only)
  DBReadReplica:
    Type: AWS::RDS::DBInstance
    Condition: IsProduction
    Properties:
      DBInstanceIdentifier: !Sub '${ProjectName}-${Environment}-db-read-replica'
      SourceDBInstanceIdentifier: !Ref DBInstance
      DBInstanceClass: !Ref DBInstanceClass
      PubliclyAccessible: false
      AutoMinorVersionUpgrade: true
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-db-read-replica'
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: ReadReplica

Conditions:
  IsProduction: !Equals [!Ref Environment, production]

Outputs:
  DBInstanceEndpoint:
    Description: RDS instance endpoint
    Value: !GetAtt DBInstance.Endpoint.Address
    Export:
      Name: !Sub '${ProjectName}-${Environment}-DBEndpoint'

  DBInstancePort:
    Description: RDS instance port
    Value: !GetAtt DBInstance.Endpoint.Port
    Export:
      Name: !Sub '${ProjectName}-${Environment}-DBPort'

  DBName:
    Description: Database name
    Value: !Ref DBName
    Export:
      Name: !Sub '${ProjectName}-${Environment}-DBName'

  VPCId:
    Description: VPC ID (default VPC used)
    Value: !Ref VpcId
    Export:
      Name: !Sub '${ProjectName}-${Environment}-VPCId'

  DBReadReplicaEndpoint:
    Condition: IsProduction
    Description: RDS read replica endpoint
    Value: !GetAtt DBReadReplica.Endpoint.Address
    Export:
      Name: !Sub '${ProjectName}-${Environment}-DBReadReplicaEndpoint'


