AWSTemplateFormatVersion: '2010-09-09'
Description: 'Flight Schedule Pro - Secrets Manager for API Keys'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - production
    Description: Environment name
  
  ProjectName:
    Type: String
    Default: flight-schedule-pro
    Description: Project name for resource naming

  OpenWeatherMapApiKey:
    Type: String
    NoEcho: true
    Description: OpenWeatherMap API Key

  WeatherApiComKey:
    Type: String
    NoEcho: true
    Description: WeatherAPI.com API Key

  AnthropicApiKey:
    Type: String
    NoEcho: true
    Description: Anthropic Claude API Key

Resources:
  # OpenWeatherMap API Key Secret
  OpenWeatherMapSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${ProjectName}/${Environment}/openweathermap-api-key'
      Description: OpenWeatherMap API Key
      SecretString: !Ref OpenWeatherMapApiKey
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # WeatherAPI.com API Key Secret
  WeatherApiComSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${ProjectName}/${Environment}/weatherapi-com-key'
      Description: WeatherAPI.com API Key
      SecretString: !Ref WeatherApiComKey
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # Anthropic API Key Secret
  AnthropicApiKeySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${ProjectName}/${Environment}/anthropic-api-key'
      Description: Anthropic Claude API Key
      SecretString: !Ref AnthropicApiKey
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # Database Credentials Secret
  DatabaseCredentialsSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${ProjectName}/${Environment}/database-credentials'
      Description: Database master credentials
      GenerateSecretString:
        SecretStringTemplate: '{"username": "postgres"}'
        GenerateStringKey: 'password'
        PasswordLength: 32
        ExcludeCharacters: '"@/\'
      # Enable automatic rotation every 90 days
      RotationRules:
        AutomaticallyAfterDays: 90
      RotationLambdaARN: !GetAtt RotationFunction.Arn
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # Rotation Lambda Function (for database credentials)
  RotationFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-${Environment}-secret-rotation'
      Runtime: python3.9
      Handler: index.lambda_handler
      Role: !GetAtt RotationFunctionRole.Arn
      Timeout: 30
      Environment:
        Variables:
          SECRETS_MANAGER_ENDPOINT: !Sub 'https://secretsmanager.${AWS::Region}.amazonaws.com'
      Code:
        ZipFile: |
          import boto3
          import json
          import os
          
          def lambda_handler(event, context):
              # Placeholder rotation function
              # In production, implement actual rotation logic
              return {
                  'statusCode': 200,
                  'body': json.dumps('Rotation function placeholder')
              }

  # IAM Role for Rotation Function
  RotationFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: SecretsManagerRotation
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:DescribeSecret
                  - secretsmanager:GetSecretValue
                  - secretsmanager:PutSecretValue
                  - secretsmanager:UpdateSecretVersionStage
                  - secretsmanager:TestSecretVersion
                Resource: !Ref DatabaseCredentialsSecret
              - Effect: Allow
                Action:
                  - rds:ModifyDBInstance
                  - rds:DescribeDBInstances
                Resource: '*'

Outputs:
  OpenWeatherMapSecretArn:
    Description: OpenWeatherMap API Key Secret ARN
    Value: !Ref OpenWeatherMapSecret
    Export:
      Name: !Sub '${ProjectName}-${Environment}-OpenWeatherMapSecretArn'

  WeatherApiComSecretArn:
    Description: WeatherAPI.com API Key Secret ARN
    Value: !Ref WeatherApiComSecret
    Export:
      Name: !Sub '${ProjectName}-${Environment}-WeatherApiComSecretArn'

  AnthropicApiKeySecretArn:
    Description: Anthropic API Key Secret ARN
    Value: !Ref AnthropicApiKeySecret
    Export:
      Name: !Sub '${ProjectName}-${Environment}-AnthropicApiKeySecretArn'

  DatabaseCredentialsSecretArn:
    Description: Database Credentials Secret ARN
    Value: !Ref DatabaseCredentialsSecret
    Export:
      Name: !Sub '${ProjectName}-${Environment}-DatabaseCredentialsSecretArn'


